name: 'Cancel this branch'
description: 'Uses the GitHub Actions API to cancel the current branch (pending only)'
inputs:
  token:
    description: 'Token'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'cancel.js'
branding:
  icon: alert-octagon
  color: purple

author: UMH Systems GmbH
